/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  text: string;
  icon?: string;
}

const Button: React.FC<ButtonProps> = ({ text, icon }) => {
  return (
    <button className="flex gap-2 justify-center self-stretch px-9 py-2 my-auto text-sm text-right bg-lime-400 rounded text-neutral-900 max-md:px-5">
      <span className="my-auto">{text}</span>
      {icon && (
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="shrink-0 w-6 aspect-square"
        />
      )}
    </button>
  );
};

export default Button;
