/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

const featuresData = [
  {
    title: "Hyperdeflationary token",
    description:
      "Total supply of 1 Billion keeps on burning during a season.",
  },
  {
    title: "Elastic Supply",
    description:
      "At the end of every season, Relaunch event sets supply to 1 Bn.",
  },
  {
    title: "Automated monetary policy",
    description:
      "The protocol runs itself throughout, managing token supply.",
  },

 
  {
    title: "Reserve Backed",
    description:
      "blackmonk tokens are bought from tax funds and collected in season reserve.",
  },
];


const Features = () => {
  return (
    <section className="flex overflow-hidden relative flex-col justify-end items-center container">
     
      <div className="relative ">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          {featuresData.map((feature, index) => (
            <div
              key={index}
              className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
            >
              <FeatureCard {...feature} />
            </div>
          ))}
        </div>
      </div>

    </section>
  );
};

export default Features;
