/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ToastContainer } from "react-toastify";



const Header = ({ logo,accounts, onConnect}) => {

  console.log({accounts,onConnect})
  const account = accounts?.length ? accounts[0].slice(0,6)+'....'+accounts[0].slice(-6) : "Connect Wallet"

  return (
    <header className="main-header flex gap-5 justify-between items-center px-5 w-full container max-md:max-w-full">

      <img
        loading="lazy"
        src={logo}
        alt="Company logo"
        className="shrink-0 self-stretch max-w-full aspect-[4] w-[187px]"
      />
      
      <nav className="flex gap-10 self-stretch my-auto text-base text-zinc-100 text-opacity-80">
        {/* <a href="#project-info">Project Info</a>
        <a href="#tokenomics">Tokenomics</a>
        <a href="#roadmap">Roadmap</a>
        <a href="#team">Team</a> */}
      </nav>
      <button onClick={onConnect} className="flex gap-2 justify-center self-stretch px-9 py-2 my-auto text-sm text-right bg-lime-400 rounded text-neutral-900 max-md:px-5">
        <span className="my-auto">{account}</span>
        {!accounts?.length&&
        
        <img
        src={"https://cdn.builder.io/api/v1/image/assets/TEMP/574eeb0fb2fda94c9fc850ebbb3d00782e68d4156aac39e2f4ed286a71dceeae?apiKey=b4d1b9e87b084579b1e2475047caf617&"}
          loading="lazy"
          alt=""
          className="shrink-0 w-6 aspect-square"
        />}
      </button>
    </header>
  );
};

export default Header;
