/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ReactDOM from "react-dom";
import HomePage from "./pages/HomePage";
import "./index.css";

ReactDOM.render(
  <React.StrictMode>
    <HomePage />
  </React.StrictMode>,
  document.getElementById("root")
);
