/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import { ToastContainer } from "react-toastify";

const Layout = ({ children, onConnect, accounts }) => {
  return (
    <div className="w-full items-center pt-5 bg-neutral-900">
      <ToastContainer />
      <Header
        accounts={accounts}
        onConnect={onConnect}
        logo="logo-white.svg"
      />
      <div className="self-stretch mt-5 w-full border border-solid bg-zinc-800 border-zinc-800 min-h-[1px] max-md:max-w-full" />
      <main>{children}</main>
    </div>
  );
};

export default Layout;
