/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Features from "./Features";
import InfoSection from "./InfoSection";
import PrivateSale from "./PrivateSale";

const MainContent: React.FC = () => {
  return (
    <main className="flex flex-col items-center pt-5 bg-neutral-900">
      <Header logo="https://cdn.builder.io/api/v1/image/assets/TEMP/6ad18aeb90ab203fe13f6b1c993da801b1a0b7e3e524fd5b6cb5c99a8b7e2ef0?apiKey=b4d1b9e87b084579b1e2475047caf617&" />
      <div className="self-stretch mt-5 w-full border border-solid bg-zinc-800 border-zinc-800 min-h-[1px] max-md:max-w-full" />
     
     
      <Hero />

      <Features />


      <div className="flex flex-col items-center px-5 mt-28 container">
        
        <InfoSection
          title="BlackMonk as DeFI"
          subtitle="Passively saving $UNI for holders"
          description="Unira DeFi protocol works for UNIRA community to save Uniswap ($UNI) tokens passively throughout the year. It is based on a tax economy just like the governments work in countries. There's a 6% fixed tax on every transaction of UNIRA token."
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/0dd04be8cc5244e20e05c7f7dcaa5943d2b4095c7d6629b8a50f24a658d7fb44?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          imageAlt="BlackMonk as DeFI illustration"
        />


        <InfoSection
          title="BlackMonk as Business DAO"
          subtitle="Passively saving $UNI for holders"
          description="Unira DeFi protocol works for UNIRA community to save Uniswap ($UNI) tokens passively throughout the year. It is based on a tax economy just like the governments work in countries. There's a 6% fixed tax on every transaction of UNIRA token."
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/0dd04be8cc5244e20e05c7f7dcaa5943d2b4095c7d6629b8a50f24a658d7fb44?apiKey=b4d1b9e87b084579b1e2475047caf617&"
          imageAlt="BlackMonk as Business DAO illustration"
          reverse={true}
        />

        <PrivateSale />
      </div>
    </main>
  );
};

export default MainContent;
