/**
 * This code was generated by Builder.io.
 */
import React from "react";



const Offer = () => {
  return (
   <>
 
<section className="flex justify-center items-center px-16 py-20 bg-neutral-900 max-md:px-5">
  <div className="pt-2 mt-5 w-full container max-md:max-w-full">

    <div className="flex gap-5 max-md:flex-col max-md:gap-0 justify-center align-middle">
      <div className="flex flex-col w-[59%] max-md:ml-0 max-md:w-full">

        <div className="flex flex-col grow items-start text-lg font-medium leading-7 text-zinc-300 max-md:mt-10 max-md:max-w-full">

          <h2 className=" text-lime-300 max-md:max-w-full">
            Earn Free Tour Package
          </h2>

          <h1 className="self-stretch mt-2 text-5xl  heading text-lime-300 leading-[56px] max-md:max-w-full max-md:text-4xl max-md:leading-[55px]">
            <span className="text-zinc-300">Buy BMONK Of $6000 And Get </span>
            <span className="text-lime-300">Free Goa Tour Package</span>
          </h1>
          <ul className="list-none pl-0">
            <li className="flex gap-4 mt-20 max-md:mt-10">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d55a713a849c85972ef39824c1e9fec22cbbb69be57470443009f5810a3757ad?apiKey=b4d1b9e87b084579b1e2475047caf617&" className="shrink-0 aspect-square w-[30px]" alt="" />
              <p>Goa 4D/3N Tour</p>
            </li>
           
            <li className="flex gap-4 mt-7">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d55a713a849c85972ef39824c1e9fec22cbbb69be57470443009f5810a3757ad?apiKey=b4d1b9e87b084579b1e2475047caf617&" className="shrink-0 aspect-square w-[30px]" alt="" />
              <p>1 Room, 1 Adults</p>
            </li>

            <li className="flex gap-4 mt-7">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/d55a713a849c85972ef39824c1e9fec22cbbb69be57470443009f5810a3757ad?apiKey=b4d1b9e87b084579b1e2475047caf617&" className="shrink-0 aspect-square w-[30px]" alt="" />
              <p>Enjoy all the sight seeings & Cruise Ride</p>
            </li>
          </ul>
          <a href="#buysection" className="flex gap-2 justify-center px-9 py-2.5 mt-7 text-base text-right bg-white rounded text-neutral-900 max-md:px-5">
            <span>Buy BMONK</span>
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/c2f7b743fc595fae685a89fb6dd18b1000578516a36565de05394387ac483cef?apiKey=b4d1b9e87b084579b1e2475047caf617&" className="shrink-0 my-auto aspect-square  w-[13px]" alt="" />
          </a>
        </div>
      </div>

      <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/976d6622f9363107e45feb37a4b1a2af75f4bb81214c7a87595f6ec0ab5f2fc6?apiKey=b4d1b9e87b084579b1e2475047caf617&" className=" w-full aspect-[0.95] max-md:mt-10 max-md:max-w-full" alt="Goa Tour Illustration" />
      </div>
    </div>
  </div>
</section>
   </>
  );
};

export default Offer;
